# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false

sqlite: &sqlite
  adapter: <%= "jdbc" if defined?(JRUBY_PLATFORM) %>sqlite3
  database: db/development.sqlite3
  timeout: 5000

development:
  <<: *postgres
  database: login_example
  username: postgres
  password: glade123

test:
  <<: *postgres
  database: login_example
  username: postgres
  password: glade123

production:
  <<: *postgres
  database: login_example
  username: postgres
  password: glade123
